add course deletion
10clouds/edx-platform pull request #36
Opened 2016-11-06 21:51 UTC by inlanger

2016-11-07 19:23 UTC, aniav requested changes

2016-11-07 19:23 UTC, aniav commented on lms/djangoapps/course_api/views.py
> +            raise ValidationError("Course with '{}' key not found.".format(course_key_string))
I am not sure this should return `400`. RFC for delete says it should be 204 in case of no entity returned.

2016-11-08 06:08 UTC, CrowbarKZ approved these changes

2016-11-08 06:08 UTC, CrowbarKZ commented on lms/djangoapps/course_api/views.py
> +        Request details for a course
shouldn't it be `Delete a course` ?

2016-11-14 15:24 UTC, inlanger commented
@aniav Could you check changes for this PR, please?

2016-11-14 21:10 UTC, aniav approved these changes

2016-11-14 21:11 UTC, aniav commented
Oh damn, sorry, I didn't know I was blocking you! :)

2016-11-15 09:45 UTC, merged